### PR TITLE
Fix TXT record serialization.

### LINKED ISSUE #268: serde_json round-trip of TXT record fails with spaces
Trying to round-trip a Txt record containing spaces with `serde_json` fails:

```rust
use domain::{base::Dname, rdata::ZoneRecordData};

type Data = ZoneRecordData<Vec<u8>, Dname<Vec<u8>>>;

fn main() {
    let a: Data = serde_json::from_str(r#"{"Txt":"test txt record"}"#).unwrap();
    println!("{:?}", a);
    let b = serde_json::to_string(&a).unwrap();
    println!("{}", b);
    let _: Data = serde_json::from_str(&b).unwrap();
}
```

Output:

```
ZoneRecordData::Txt(Txt(test\32txt\32record))
{"Txt":["test\\32txt\\32record"]}
thread 'main' panicked at src/main.rs:10:44:
called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"test\\\\32txt\\\\32record\", expected a borrowed string", line: 1, column: 31)
```

My impression is that the TXT record wire format isn't supposed to do any sort of escaping, so it's strange to see this here.

### PR DESCRIPTION
**Pull request by partim**
This PR fixes TXT record data serialization for human-readable formats. TXT record data is now serialized as a sequence of character strings. It also deserializes from such a sequence. If supported by the format, it alternatively deserializes from a string that is broken up into 255 octet chunks if necessary.

It uses a newly added helper type `base::charstr::DeserializeCharStrSeed` that deserializes character strings by appending them to an octets builder. Since this may be useful for other cases, it has been made public.

This is a breaking change.

This fixes #268.

### CODE REVIEW

File: src/base/charstr.rs [hunk 1]
```diff
@@ -295,6 +295,35 @@ impl CharStr<[u8]> {
             .map(|bytes| unsafe { Self::from_slice_unchecked(bytes) })
             .map_err(Into::into)
     }
+
+    /// Decodes the readable epresentation and appends it to a builder.
```
Comment (Philip-NLnetLabs) [inline src/base/charstr.rs:299]:
```suggestion
    /// Decodes the readable presentation and appends it to a builder.
```

**Review by Philip-NLnetLabs — APPROVED** [review]
Looks good to me
