### PR TITLE
fix: create directories under working copy only

### LINKED ISSUE #87: feature = "interop" tests create directories outside of working copy
Just noticed the extra `target` dir when cleaning up after my PRs.

The files are (relative to `Cargo.toml` when executing `cargo test --all-features`):
- `../target/test/tsig_client_nsd/nsd.conf`
- `../target/test/tsig_client_sequence_nsd/nsd.conf`

I wonder if this is because I do not have the `nsd` binary installed?

### PR DESCRIPTION
**Pull request by koivunej**
Closes #87.

### CODE REVIEW

File: src/tsig/interop.rs [hunk 1]
```diff
@@ -36,7 +36,7 @@ fn tsig_client_nsd() {
     let rng = SystemRandom::new();
 
     let cur_dir = env::current_dir().unwrap();
```
Comment (koivunej) [inline src/tsig/interop.rs:38]: Just re-tested this, it would seem that this is set to the directory of `Cargo.toml` before executing the tests. However [rust book](https://doc.rust-lang.org/book/ch11-02-running-tests.html#running-tests-in-parallel-or-consecutively) doesn't consider the working directory to be relied on, so I'll add a PR to do this relative to CARGO_MANIFEST_DIR per [shepmasters SO answer](https://stackoverflow.com/a/30004252).

**Comment by partim** [comment]
Thanks again for the fixes!
