### PR TITLE
Fix generation of domain name for IPv6 reverse lookup.

### LINKED ISSUE #131: lookup example cannot resolve IPv6 address
```
$  target/debug/examples/lookup example.org
Found answer for example.org
example.org has address 2606:2800:220:1:248:1893:25c8:1946
example.org has address 93.184.216.34
$  target/debug/examples/lookup 93.184.216.34
$  target/debug/examples/lookup 2606:2800:220:1:248:1893:25c8:1946
thread 'main' panicked at 'internal error: entered unreachable code', src/resolv/lookup/addr.rs:137:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by partim**
Fixes #131.

### CODE REVIEW

File: src/resolv/lookup/addr.rs [hunk 1]
```diff
@@ -137,3 +138,31 @@ fn hexdigit(nibble: u8) -> u8 {
...
+
+    #[test]
+    fn test_dname_from_addr() {
+        assert_eq!(
+            dname_from_addr([192, 0, 2, 12].into()),
+            Dname::<Octets128>::from_str("12.2.0.192.in-addr.arpa").unwrap()
+        );
+        assert_eq!(
+            dname_from_addr(
+                [0x2001, 0xdb8, 0x2c88, 0x0, 0xfff, 0x1, 0x1200, 0xc032]
```
Comment (pemensik) [inline src/resolv/lookup/addr.rs:157]: could maybe the tested address contain all hex digits possible? Including fixed 9?

Comment (partim) [reply src/resolv/lookup/addr.rs:157]: It should, yes!

**Review by pemensik — APPROVED** [review]
