### PR TITLE
Redefine stub resolver transport types.

### LINKED ISSUE #91: domain::resolv::stub::StubResolver doesn't fail over to TCP if there's no TCP entry in the ResolvConf
This might not be a bug, but it's perhaps surprising that the stub resolver doesn't fail over to TCP on truncation unless there's TCP explicitly added in the ResolvConf::servers. I would assume that adding a server with protocol UDP means you prefer to talk to that server over UDP, but failover on truncation would work. Similarly, if you add a server with protocol TCP it means you prefer to talk to server over TCP and there failover on truncation doesn't apply. I am happy to add a PR but thought I would open a ticket first to get your input on what would be the best way to solve this. I would probably make the failover to TCP on TC automatic with no changes to the API, but it would also work if you added something like `Protocol::UdpOrTcp` or convey this through some other way.

### PR DESCRIPTION
**Pull request by partim**
This PR redefines the stub resolver’s `Transport::Udp` type to be `Transport::UdpTcp`, i.e., use UDP but retry with TCP if the answer is truncated and slightly reworks the server selection code in the stub resolver to use all servers if `use_vc` is set.

This is a breaking change.

Fixes #91.

### CODE REVIEW

File: src/resolv/stub/mod.rs [hunk 1]
```diff
@@ -146,35 +146,29 @@ impl StubResolver {
...
+        for s in &self.servers {
+            // This assumes that Transport only has UdpTcp and Tcp. Sadly, a
+            // match doesn’t work here because of the use_cv flag.
+            if self.options.use_vc || matches!(s.transport, Transport::Tcp) {
+                let (conn, tran) =
+                    multi_stream::Connection::new(TcpConnect::new(s.addr));
+                // Start the run function on a separate task.
+                let run_fut = tran.run();
+                fut_list_tcp.push(async move {
+                    run_fut.await;
```
Comment (gthess) [inline src/resolv/stub/mod.rs:159]: Is `let run_fut` still needed here?
```suggestion
                fut_list_tcp.push(async move {
                    tran.run().await;
```

**Review by Philip-NLnetLabs — APPROVED** [review]
